-- 공개 범위 Enum 생성 (PUBLIC, FRIENDS, PRIVATE)
CREATE TYPE post_visibility AS ENUM ('PUBLIC', 'FRIENDS', 'PRIVATE');

-- 게시글 테이블 생성
CREATE TABLE posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title      VARCHAR(255) NOT NULL,
    content    TEXT NOT NULL,
    visibility post_visibility NOT NULL DEFAULT 'PUBLIC',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);