-- 기존 테이블이 있다면 완전히 삭제 (초기화)
DROP TABLE IF EXISTS post_photos CASCADE;
DROP TABLE IF EXISTS post_days CASCADE;
DROP TABLE IF EXISTS post_members CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

-- 공개범위 Enum 타입 생성 (이미 있으면 재사용)
DO $$ BEGIN
    CREATE TYPE post_visibility AS ENUM ('PUBLIC', 'FRIENDS', 'PRIVATE');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- [게시글 메인] 전체 여행 정보
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    visibility post_visibility NOT NULL DEFAULT 'PUBLIC',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- [동행 친구] 함께 간 친구 목록
CREATE TABLE post_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- [일차별 일기] 1일차, 2일차 각각의 제목과 본문
CREATE TABLE post_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    day_number INT NOT NULL,               -- 1일차, 2일차
    date DATE NOT NULL,                     -- 2026-10-01
    title VARCHAR(255) NOT NULL,            -- 해당 일차 제목
    content TEXT NOT NULL,                  -- 해당 일차 본문 (서식 HTML/JSON)
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- [사진 & 위치/시간] 각 일차에 첨부된 사진들과 카카오 마커 좌표
CREATE TABLE post_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_day_id BIGINT NOT NULL REFERENCES post_days(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,                -- Supabase Storage 업로드 URL
    taken_at TIMESTAMPTZ,                   -- 메타데이터에서 가져온 시간 (수정 가능)
    place_name VARCHAR(255),                -- 메타데이터/카카오에서 가져온 장소명
    address VARCHAR(255),                   -- 상세 주소
    latitude DOUBLE PRECISION,              -- 카카오맵 위도
    longitude DOUBLE PRECISION,             -- 카카오맵 경도
    order_index INT DEFAULT 0 NOT NULL,     -- 사진 표시 순서
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 개발용 RLS 비활성화 (테스트 시 에러 방지)
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_days DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_photos DISABLE ROW LEVEL SECURITY;